'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Customer
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Spa_Appointment_Management_System.Customer", GetType(Customer).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnNext_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnNext.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnNext2_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnNext2.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnPrevious_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnPrevious.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnPrevious2_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnPrevious2.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property BunifuTextbox3_BackgroundImage() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("BunifuTextbox3.BackgroundImage", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property BunifuTextbox3_Icon() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("BunifuTextbox3.Icon", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property BunifuTextbox4_BackgroundImage() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("BunifuTextbox4.BackgroundImage", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property BunifuTextbox4_Icon() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("BunifuTextbox4.Icon", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property BunifuTextbox7_BackgroundImage() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("BunifuTextbox7.BackgroundImage", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property BunifuTextbox7_Icon() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("BunifuTextbox7.Icon", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property Customer_ID_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Customer_ID.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
    '''</summary>
    Friend Shared ReadOnly Property CUSTOMERBindingSource_TrayLocation() As System.Drawing.Point
        Get
            Dim obj As Object = ResourceManager.GetObject("CUSTOMERBindingSource.TrayLocation", resourceCulture)
            Return CType(obj,System.Drawing.Point)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Point similar to {X=328,Y=17}.
    '''</summary>
    Friend Shared ReadOnly Property CUSTOMERTableAdapter_TrayLocation() As System.Drawing.Point
        Get
            Dim obj As Object = ResourceManager.GetObject("CUSTOMERTableAdapter.TrayLocation", resourceCulture)
            Return CType(obj,System.Drawing.Point)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property EmailTextBox1_BackgroundImage() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("EmailTextBox1.BackgroundImage", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property EmailTextBox1_Icon() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("EmailTextBox1.Icon", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property EmailTextBox1_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("EmailTextBox1.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property GunaCircleButton1_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("GunaCircleButton1.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property GunaCircleButton2_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("GunaCircleButton2.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property GunaCircleButton3_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("GunaCircleButton3.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property GunaCircleButton4_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("GunaCircleButton4.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property GunaCircleButton5_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("GunaCircleButton5.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property GunaCircleButton6_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("GunaCircleButton6.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property GunaCircleButton7_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("GunaCircleButton7.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property GunaCircleButton8_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("GunaCircleButton8.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property MetroTextBox7_Icon() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("MetroTextBox7.Icon", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PictureBox1_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PictureBox1.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PictureBox2_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PictureBox2.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Point similar to {X=211,Y=17}.
    '''</summary>
    Friend Shared ReadOnly Property ShangrilaDS_TrayLocation() As System.Drawing.Point
        Get
            Dim obj As Object = ResourceManager.GetObject("ShangrilaDS.TrayLocation", resourceCulture)
            Return CType(obj,System.Drawing.Point)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Textbox1_BackgroundImage() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Textbox1.BackgroundImage", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Textbox1_Icon() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Textbox1.Icon", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Textbox2_BackgroundImage() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Textbox2.BackgroundImage", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Textbox2_Icon() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Textbox2.Icon", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Textbox6_BackgroundImage() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Textbox6.BackgroundImage", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Textbox6_Icon() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Textbox6.Icon", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Textbox7_BackgroundImage() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Textbox7.BackgroundImage", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Textbox7_Icon() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Textbox7.Icon", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Textbox8_BackgroundImage() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Textbox8.BackgroundImage", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property Textbox8_Icon() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("Textbox8.Icon", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Point similar to {X=516,Y=17}.
    '''</summary>
    Friend Shared ReadOnly Property ToolTip1_TrayLocation() As System.Drawing.Point
        Get
            Dim obj As Object = ResourceManager.GetObject("ToolTip1.TrayLocation", resourceCulture)
            Return CType(obj,System.Drawing.Point)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property ZipCodeTextBox_BackgroundImage() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ZipCodeTextBox.BackgroundImage", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property ZipCodeTextBox_Icon() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ZipCodeTextBox.Icon", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
End Class
